const routes = {
    home: '/',
    login: '/login',
    register: '/register',
    history: '/history',
    cart: '/cart',
    products: '/products',
    productsByCategory: '/products/:category',
    productByID: '/products/:category/:id',
    profile: '/account/:userid/profile',
    purchase: '/account/:userid/purchase',
    shop: '/shop/:shipId',
    password: '/account/:userid/password',
    checkout: '/checkout',
    thankpage: '/api/v1/paymentsuccess',
    // Seller
    registerSeller: '/seller/register',
    dashboard: '/seller/dashboard',
    order: '/seller/order',
    product: '/seller/product/all',
    createProduct: '/seller/product/create',
    updateProduct: '/seller/product/update/:id',
    delivery: '/seller/delivery',
    profileSeller: '/seller/profile',
    orderDetail: '/seller/order/detail/:id',
    //Admin
    shopAdmin: '/admin/shop',
    editShop: '/admin/shop/update/:id',
    dashboardAdmin: '/admin/dashboard',
    loginAdmin: '/admin/login',
    customers: '/admin/customers',
    createUser: '/admin/customers/create',
    updateUser: '/admin/customers/update/:id',
    ordersAdmin: '/admin/orders',
    orderDetails: '/admin/orders/:id',
    productsAdmin: '/admin/products',
    mailingList: '/admin/mailinglist',
};

export default routes;
